### ISSUE TITLE
Current docker version fails when attempting to create a superuser using seatable.sh

### ISSUE THREAD

**Issue by alazare619** [seatable/seatable#39]
```
ash-4.3# docker exec -it seatable /shared/seatable/scripts/seatable.sh superuser
E-mail address: alazare619@github.com
Password:
Password (again):
Traceback (most recent call last):
  File "/opt/seatable/seatable-server-latest/dtable-web/thirdpart/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/opt/seatable/seatable-server-latest/dtable-web/thirdpart/django/db/backends/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "/opt/seatable/seatable-server-latest/dtable-web/thirdpart/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/opt/seatable/seatable-server-latest/dtable-web/thirdpart/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/opt/seatable/seatable-server-latest/dtable-web/thirdpart/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/opt/seatable/seatable-server-latest/dtable-web/thirdpart/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/opt/seatable/seatable-server-latest/dtable-web/thirdpart/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/opt/seatable/seatable-server-latest/dtable-web/thirdpart/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/opt/seatable/seatable-server-latest/dtable-web/thirdpart/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/opt/seatable/seatable-server-latest/dtable-web/thirdpart/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'dtable_db.profile_profile' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/seatable/seatable-server-latest/dtable-web/thirdpart/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/opt/seatable/seatable-server-latest/dtable-web/thirdpart/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/seatable/seatable-server-latest/dtable-web/thirdpart/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/seatable/seatable-server-latest/dtable-web/thirdpart/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/opt/seatable/seatable-server-0.9.5/dtable-web/seahub/base/management/commands/createsuperuser.py", line 150, in handle
    User.objects.create_superuser(email, password)
  File "/opt/seatable/seatable-server-0.9.5/dtable-web/seahub/base/accounts.py", line 89, in create_superuser
    u = self.create_user(email, password, is_staff=True, is_active=True)
  File "/opt/seatable/seatable-server-0.9.5/dtable-web/seahub/base/accounts.py", line 58, in create_user
    Profile.objects.add_or_update(username=virtual_id, contact_email=email)
  File "/opt/seatable/seatable-server-0.9.5/dtable-web/seahub/profile/models.py", line 29, in add_or_update
    profile = self.get(user=username)
  File "/opt/seatable/seatable-server-latest/dtable-web/thirdpart/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/seatable/seatable-server-latest/dtable-web/thirdpart/django/db/models/query.py", line 374, in get
    num = len(clone)
  File "/opt/seatable/seatable-server-latest/dtable-web/thirdpart/django/db/models/query.py", line 232, in __len__
    self._fetch_all()
  File "/opt/seatable/seatable-server-latest/dtable-web/thirdpart/django/db/models/query.py", line 1121, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/opt/seatable/seatable-server-latest/dtable-web/thirdpart/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
  File "/opt/seatable/seatable-server-latest/dtable-web/thirdpart/django/db/models/sql/compiler.py", line 899, in execute_sql
    raise original_exception
  File "/opt/seatable/seatable-server-latest/dtable-web/thirdpart/django/db/models/sql/compiler.py", line 889, in execute_sql
    cursor.execute(sql, params)
  File "/opt/seatable/seatable-server-latest/dtable-web/thirdpart/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/opt/seatable/seatable-server-latest/dtable-web/thirdpart/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/opt/seatable/seatable-server-latest/dtable-web/thirdpart/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/opt/seatable/seatable-server-latest/dtable-web/thirdpart/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/opt/seatable/seatable-server-latest/dtable-web/thirdpart/django/db/backends/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "/opt/seatable/seatable-server-latest/dtable-web/thirdpart/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/opt/seatable/seatable-server-latest/dtable-web/thirdpart/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/opt/seatable/seatable-server-latest/dtable-web/thirdpart/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/opt/seatable/seatable-server-latest/dtable-web/thirdpart/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/opt/seatable/seatable-server-latest/dtable-web/thirdpart/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/opt/seatable/seatable-server-latest/dtable-web/thirdpart/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/opt/seatable/seatable-server-latest/dtable-web/thirdpart/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/opt/seatable/seatable-server-latest/dtable-web/thirdpart/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.ProgrammingError: (1146, "Table 'dtable_db.profile_profile' doesn't exist")

**Comment by freeplant** [comment]
This is because you run the command before the database initialization finishing. We have updated our document: 

![image](https://user-images.githubusercontent.com/109339/80201518-d78ef080-8656-11ea-909f-dca427d6c7d0.png)

**Comment by alazare619** [comment]
Ill give it a go again here shortly definetly looked like it was misssing tables which would explain it wasn't ready yet.

**Comment by alazare619** [comment]
thatworked @freeplant  Ill c lose the ticket now thank you very much
