### ISSUE TITLE
Sometimes the export of a view crash, maybe related to column's names

### ISSUE THREAD

**Issue by mdartic** [seatable/seatable#97]
I've encountered bugs during exports of table.

I'm not sure, but it could related to column's names.

After some deletions of columns, export work again.

Here are some samples of error logs :

```
  File "/opt/seatable/seatable-server-latest/dtable-web/thirdpart/openpyxl/utils/cell.py", line 123, in column_index_from_string
    raise ValueError("{0} is not a valid column name".format(str_col))
ValueError: | is not a valid column name
2020-06-26 09:27:28,149 [ERROR] django.request:135 handle_uncaught_exception Internal Server Error: /api/v2.1/workspace/2/dtable/Base principale/export-excel/
Traceback (most recent call last):
  File "/opt/seatable/seatable-server-latest/dtable-web/thirdpart/openpyxl/utils/cell.py", line 121, in column_index_from_string
    return _COL_STRING_CACHE[str_col.upper()]
KeyError: '{'


  File "/opt/seatable/seatable-server-latest/dtable-web/thirdpart/openpyxl/utils/cell.py", line 123, in column_index_from_string
    raise ValueError("{0} is not a valid column name".format(str_col))
ValueError:  is not a valid column name
2020-06-26 09:32:39,395 [ERROR] django.request:135 handle_uncaught_exception Internal Server Error: /api/v2.1/workspace/2/dtable/Base principale/export-excel/
Traceback (most recent call last):
  File "/opt/seatable/seatable-server-latest/dtable-web/thirdpart/openpyxl/utils/cell.py", line 121, in column_index_from_string
    return _COL_STRING_CACHE[str_col.upper()]
KeyError: '|'

  File "/opt/seatable/seatable-server-latest/dtable-web/thirdpart/openpyxl/utils/cell.py", line 123, in column_index_from_string
    raise ValueError("{0} is not a valid column name".format(str_col))
ValueError: { is not a valid column name
2020-06-26 09:29:20,229 [ERROR] django.request:135 handle_uncaught_exception Internal Server Error: /api/v2.1/workspace/2/dtable/Base principale/export-excel/
Traceback (most recent call last):
  File "/opt/seatable/seatable-server-latest/dtable-web/thirdpart/openpyxl/utils/cell.py", line 121, in column_index_from_string
    return _COL_STRING_CACHE[str_col.upper()]
KeyError: '\x84'

  File "/opt/seatable/seatable-server-latest/dtable-web/thirdpart/openpyxl/utils/cell.py", line 123, in column_index_from_string
    raise ValueError("{0} is not a valid column name".format(str_col))
ValueError: 
             is not a valid column name
2020-06-26 09:29:54,449 [ERROR] django.request:135 handle_uncaught_exception Internal Server Error: /api/v2.1/workspace/2/dtable/Base principale/export-excel/
Traceback (most recent call last):
  File "/opt/seatable/seatable-server-latest/dtable-web/thirdpart/openpyxl/utils/cell.py", line 121, in column_index_from_string
    return _COL_STRING_CACHE[str_col.upper()]
KeyError: '\x83'

  File "/opt/seatable/seatable-server-latest/dtable-web/thirdpart/openpyxl/utils/cell.py", line 123, in column_index_from_string
    raise ValueError("{0} is not a valid column name".format(str_col))
ValueError:  is not a valid column name
2020-06-26 09:30:18,123 [ERROR] django.request:135 handle_uncaught_exception Internal Server Error: /api/v2.1/workspace/2/dtable/Base principale/export-excel/
Traceback (most recent call last):
  File "/opt/seatable/seatable-server-latest/dtable-web/thirdpart/openpyxl/utils/cell.py", line 121, in column_index_from_string
    return _COL_STRING_CACHE[str_col.upper()]
KeyError: '\x82'

  File "/opt/seatable/seatable-server-latest/dtable-web/thirdpart/openpyxl/utils/cell.py", line 123, in column_index_from_string
    raise ValueError("{0} is not a valid column name".format(str_col))
ValueError:  is not a valid column name
2020-06-26 09:30:36,684 [ERROR] django.request:135 handle_uncaught_exception Internal Server Error: /api/v2.1/workspace/2/dtable/Base principale/export-excel/
Traceback (most recent call last):
  File "/opt/seatable/seatable-server-latest/dtable-web/thirdpart/openpyxl/utils/cell.py", line 121, in column_index_from_string
    return _COL_STRING_CACHE[str_col.upper()]
KeyError: '\x81'

  File "/opt/seatable/seatable-server-latest/dtable-web/thirdpart/openpyxl/utils/cell.py", line 123, in column_index_from_string
    raise ValueError("{0} is not a valid column name".format(str_col))
ValueError:  is not a valid column name
2020-06-26 09:32:00,323 [ERROR] django.request:135 handle_uncaught_exception Internal Server Error: /api/v2.1/workspace/2/dtable/Base principale/export-excel/
Traceback (most recent call last):
  File "/opt/seatable/seatable-server-latest/dtable-web/thirdpart/openpyxl/utils/cell.py", line 121, in column_index_from_string
    return _COL_STRING_CACHE[str_col.upper()]
KeyError: '\x80'

  File "/opt/seatable/seatable-server-latest/dtable-web/thirdpart/openpyxl/utils/cell.py", line 123, in column_index_from_string
    raise ValueError("{0} is not a valid column name".format(str_col))
ValueError:  is not a valid column name
2020-06-26 09:32:06,327 [ERROR] django.request:135 handle_uncaught_exception Internal Server Error: /api/v2.1/workspace/2/dtable/Base principale/export-excel/
Traceback (most recent call last):
  File "/opt/seatable/seatable-server-latest/dtable-web/thirdpart/openpyxl/utils/cell.py", line 121, in column_index_from_string
    return _COL_STRING_CACHE[str_col.upper()]
KeyError: '\x7f'

  File "/opt/seatable/seatable-server-latest/dtable-web/thirdpart/openpyxl/utils/cell.py", line 123, in column_index_from_string
    raise ValueError("{0} is not a valid column name".format(str_col))
ValueError: { is not a valid column name
2020-06-26 09:35:19,676 [ERROR] django.request:135 handle_uncaught_exception Internal Server Error: /api/v2.1/workspace/2/dtable/Base principale/export-excel/
Traceback (most recent call last):
  File "/opt/seatable/seatable-server-latest/dtable-web/thirdpart/openpyxl/utils/cell.py", line 121, in column_index_from_string
    return _COL_STRING_CACHE[str_col.upper()]
KeyError: '\\'

  File "/opt/seatable/seatable-server-latest/dtable-web/thirdpart/openpyxl/utils/cell.py", line 123, in column_index_from_string
    raise ValueError("{0} is not a valid column name".format(str_col))
ValueError: \ is not a valid column name
2020-06-26 09:35:43,187 [ERROR] django.request:135 handle_uncaught_exception Internal Server Error: /api/v2.1/workspace/2/dtable/Base principale/export-excel/
Traceback (most recent call last):
  File "/opt/seatable/seatable-server-latest/dtable-web/thirdpart/openpyxl/utils/cell.py", line 121, in column_index_from_string
    return _COL_STRING_CACHE[str_col.upper()]
KeyError: '_'

  File "/opt/seatable/seatable-server-latest/dtable-web/thirdpart/openpyxl/utils/cell.py", line 123, in column_index_from_string
    raise ValueError("{0} is not a valid column name".format(str_col))
ValueError: _ is not a valid column name
 
```

Hope that could help...

**Comment by freeplant** [comment]
The fix will be included in version 1.1
